#!/bin/bash

# default value
es_host=127.0.0.1
es_port=9200
es_container=elasticsearch
register_path="/usr/share/elasticsearch/backup"
from_step=0

while (($#)); do
    case $1 in
        "--eshost" | "-eh")
            shift
            es_host=$1
            shift
        ;;
        "--esport" | "-ep")
            shift
            es_port=$1
            shift
        ;;
        "--escontainer" | "-ec")
            shift
            es_container=$1
            shift
        ;;
        "--index" | "-i")
            shift
            index=$1
            shift
        ;;
        "--repo" | "-r")
            shift
            repo=$1
            shift
        ;;
        "--snapshot" | "-s")
            shift
            snapshot=$1
            shift
        ;;
        "--register-path" | "-rp")
            shift
            register_path=$1
            shift
        ;;
        "--target" | "-t")
            shift
            target=$1
            shift
        ;;
        "--from-step" | "-f")
            shift
            from_step=$1
            shift
        ;;
        "--help" | "-h")
            echo "Required options:"
            echo "    --repo <repository>, -r <repository>"
            echo "        Snapshot repository name."
            echo "    --snapshot <snapshot>, -s <snapshot>"
            echo "        Snapshot name."
            echo "    --target <path>, -t <path>"
            echo "        Target path of backup folder."
            echo "    --index <index>, -i <index>"
            echo "        Index that specified to be imported."
            echo
            echo "Optional options:"
            echo "    --eshost <host>, -eh <host>"
            echo "        Elasticsearch service host. Default: 127.0.0.1"
            echo "    --esport <port>, -ep <port>"
            echo "        Elasticsearch service port. Default: 9200"
            echo "    --escontainer <container name>, -ec <continer name>"
            echo "        Elasticsearch docker container name. Default: elasticsearch"
            echo "    --register-path <path>, -rp <path>"
            echo "        Path of snapshot repository. Used for registering repository if repository doesn't exists. Default: /usr/share/elasticsearch/backup"
            echo "    --from-step <step>, -f <step>"
            echo "        Start from which step. Default: 1"
            exit 0
        ;;
        *)
            echo "unknown argument '$1'"
            echo "Use --help (or -h) to get the usage information."
            exit 1
    esac
done

if [ -z "$repo" ]; then
    echo "Option --repo is required."
    exit 1
fi

if [ -z "$snapshot" ]; then
    echo "Option --snapshot is required."
    exit 1
fi

if [ -z "$target" ]; then
    echo "Option --target is required."
    exit 1
fi

if [ -z "$index" ]; then
    echo "--index is required."
    exit 1
fi

# check if the index exists.
if [ $from_step -le 1 ]; then
    echo "[Step 1] Check if the index exists."
    resp=$(curl --silent --fail-with-body "http://$es_host:$es_port/_cat/indices/$index")

    if [ "$(echo $resp | grep " $index ")" != "" ]; then
        echo "[Step 1] Index '$index' exists. You can remove it by 'DELETE http://$es_host:$es_port/$index'."
        exit 1
    else
        echo "[Step 1] Index '$index' doesn't exist."
    fi
fi

# remove existing repository
if [ $from_step -le 2 ]; then
    echo "[Step 2] Check if the repository '$repo' is registered."
    curl --silent --fail-with-body "http://$es_host:$es_port/_snapshot/$repo"

    if [ $? -eq 0 ]; then
        echo
        echo "[Step 2] Repository has already registered. Unregister it."
        curl -X DELETE --silent --fail-with-body "http://$es_host:$es_port/_snapshot/$repo"
        if [ $? -eq 0 ]; then
            echo
            echo "[Step 2] Unregister succeed."
        else
            echo
            echo "[Step 2] Unregister failed."
            exit 1
        fi
    else
        echo "[Step 2] Repository hasn't registered."
    fi
fi

# clean folder
if [ $from_step -le 3 ]; then
    echo "[Step 3] Remove snapshot files at snapshot repository."
    docker exec -i $es_container rm -rf "$register_path"

    if [ $? -eq 0 ]; then
        echo "[Step 3] Remove succeed."
    else
        echo "[Step 3] Remove failed."
        exit 1
    fi
    docker exec -i $es_container mkdir "$register_path"
fi

# copy files
if [ $from_step -le 4 ]; then
    echo "[Step 4] Copy files from '$target' to snapshot repository folder."
    docker cp $target/. $es_container:$register_path/

    if [ $? -eq 0 ]; then
        echo "[Step 4] Copy succeed."
    else
        echo "[Step 4] Copy failed. You can retry from this step with option '--from-step 4'."
        exit 1
    fi
fi

# modify ownership
if [ $from_step -le 5 ]; then
    echo "[Step 5] Modify ownership of snapshot repository folder."
    docker exec -i $es_container chown -R elasticsearch:root $register_path

    if [ $? -eq 0 ]; then
        echo "[Step 5] Modify succeed."
    else
        echo "[Step 5] Modify failed. You can retry from this step with option '--from-step 5'."
        exit 1
    fi
fi

# register repository
if [ $from_step -le 6 ]; then
    echo "[Step 6] Register repository."
    curl --fail-with-body -X PUT "http://$es_host:$es_port/_snapshot/$repo" \
        -H "Content-Type: application/json" \
        -d "{\"type\":\"fs\",\"settings\":{\"location\":\"$register_path\"}}"
    
    if [ $? -eq 0 ]; then
        echo
        echo "[Step 6] Register succeed."
    else
        echo
        echo "[Step 6] Register failed. You can retry from this step with option '--from-step 6'."
        exit 1
    fi
fi

# get snapshot details
if [ $from_step -le 7 ]; then
    echo "[Step 7] check if snapshot is loaded successfully."
    resp=$(curl --silent --fail-with-body "http://$es_host:$es_port/_snapshot/$repo/$snapshot")

    if [ $? -ne 0 ]; then
        echo "[Step 7] Getting snapshot details failed.  You can retry from this step with option '--from-step 7'."
        echo "[Step 7] Error response:"
        echo $resp
        exit 1
    fi

    if [ ! -z "$(echo $resp | grep $snapshot)" ]; then
        echo "[Step 7] Snapshot is loaded."
    else
        echo "[Step 7] Snapshot doesn't exist. You can retry from this step with option '--from-step 7'."
        exit 1
    fi
fi

# restore
if [ $from_step -le 8 ]; then
    echo "[Step 8] Start restoring."
    
    curl --fail-with-body -X POST "http://$es_host:$es_port/_snapshot/$repo/$snapshot/_restore?wait_for_completion=true" \
        -H "Content-Type: application/json" \
        -d "{\"indices\":\"$index\"}"

    if [ $? -eq 0 ]; then
        echo
        echo "[Step 8] Restore succeed."
    else
        echo
        echo "[Step 8] Restore failed. You can retry from this step with option '--from-step 8'."
        exit 1
    fi
fi

echo
echo "Done!!"
